import {
  AchievementCategory,
  AchievementRarity,
  AchievementConditionType,
  AchievementConditionOperator,
  AchievementScope,
} from '../entities/achievement.entity';

export const ACHIEVEMENT_DEFINITIONS = [
  // ==================== PRECISION (🏆) - Skill-based ====================
  {
    key: 'first_bet',
    name: 'Premier Pari',
    description: 'Placer votre premier pari',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.COMMON,
    icon: '🏆',
    xpReward: 10,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'perfect_podium',
    name: 'Podium Parfait',
    description: 'Prédire le podium exact',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '🏆',
    xpReward: 50,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'perfectBets',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'perfect_prophet',
    name: 'Le Prophète',
    description: '5 podiums parfaits',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏆',
    xpReward: 500,
    unlocksTitle: 'Le Prophète',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'perfectBets',
      operator: AchievementConditionOperator.GTE,
      value: 5,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'sniper',
    name: 'Sniper',
    description: '10 paris avec 2/3 picks corrects',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '🎯',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'partialWins',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'sharpshooter',
    name: "Tireur d'élite",
    description: '50% win rate sur 20+ paris',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.EPIC,
    icon: '🎯',
    xpReward: 250,
    unlocksTitle: 'Sniper',
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate',
      operator: AchievementConditionOperator.GTE,
      value: 50,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'expert_bettor',
    name: 'Parieur Expert',
    description: '75% win rate sur 20+ paris',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏆',
    xpReward: 500,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate',
      operator: AchievementConditionOperator.GTE,
      value: 75,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== REGULARITY (🌟) - Engagement ====================
  {
    key: 'five_bets',
    name: 'Habitué',
    description: '5 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.COMMON,
    icon: '🌟',
    xpReward: 25,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 5,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'twenty_bets',
    name: 'Vétéran',
    description: '20 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🌟',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 20,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'fifty_bets',
    name: 'Légende',
    description: '50 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🌟',
    xpReward: 300,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 50,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'weekly_warrior',
    name: 'Guerrier Hebdo',
    description: '4 semaines consécutives',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🔥',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'monthlyStreak',
      operator: AchievementConditionOperator.GTE,
      value: 4,
    },
  },
  {
    key: 'monthly_master',
    name: 'Maître Mensuel',
    description: '12 semaines consécutives',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🔥',
    xpReward: 300,
    unlocksTitle: 'Régulier',
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'monthlyStreak',
      operator: AchievementConditionOperator.GTE,
      value: 12,
    },
  },
  {
    key: 'iron_streak',
    name: 'Série de Fer',
    description: 'Record lifetime 20 semaines',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '⭐',
    xpReward: 500,
    unlocksTitle: "L'Invincible",
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'lifetimeStreak',
      operator: AchievementConditionOperator.GTE,
      value: 20,
    },
  },
  {
    key: 'never_give_up',
    name: 'Jamais Abandonner',
    description: 'Parier après 5 semaines perdantes',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '💪',
    xpReward: 150,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'comebackBets',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== AUDACITY (🎯) - Risk-taking ====================
  {
    key: 'first_boost',
    name: 'Première Turbo',
    description: 'Utiliser le boost x2',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.COMMON,
    icon: '⚡',
    xpReward: 20,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'boostsUsed',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'boost_master',
    name: 'Maître Turbo',
    description: 'Utiliser boost 3 mois consécutifs',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.RARE,
    icon: '⚡',
    xpReward: 150,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveBoostMonths',
      operator: AchievementConditionOperator.GTE,
      value: 3,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'turbo_king',
    name: 'Roi Turbo',
    description: 'Utiliser boost 6 mois consécutifs',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '⚡',
    xpReward: 500,
    unlocksTitle: 'Turbo King',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveBoostMonths',
      operator: AchievementConditionOperator.GTE,
      value: 6,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'high_roller',
    name: 'Flambeur',
    description: 'Parier sur outsider (odds > 10) et gagner',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.EPIC,
    icon: '🎲',
    xpReward: 250,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'highOddsWins',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'all_in',
    name: 'All-In',
    description: 'Boost sur outsider (odds > 10) et gagner',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🎲',
    xpReward: 500,
    unlocksTitle: 'Le Flambeur',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'boostedHighOddsWins',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== RANKING (🏅) - Competitive ====================
  {
    key: 'top_ten',
    name: 'Top 10',
    description: 'Terminer dans le top 10 mensuel',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.RARE,
    icon: '🏅',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.LTE,
      value: 10,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'podium_finish',
    name: 'Sur le Podium',
    description: 'Terminer dans le top 3 mensuel',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '🥉',
    xpReward: 300,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.LTE,
      value: 3,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'monthly_champion',
    name: 'Champion Mensuel',
    description: 'Terminer 1er du mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏆',
    xpReward: 500,
    unlocksTitle: 'Champion',
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.EQ,
      value: 1,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'back_to_back',
    name: 'Double Champion',
    description: '1er deux mois consécutifs',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '👑',
    xpReward: 1000,
    unlocksTitle: 'Dominateur',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveMonthlyWins',
      operator: AchievementConditionOperator.GTE,
      value: 2,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'points_machine',
    name: 'Machine à Points',
    description: 'Gagner 500 points en un mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '💯',
    xpReward: 250,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'totalPoints',
      operator: AchievementConditionOperator.GTE,
      value: 500,
      scope: AchievementScope.MONTHLY,
    },
  },
];
