import {
  AchievementCategory,
  AchievementRarity,
  AchievementConditionType,
  AchievementConditionOperator,
  AchievementScope,
} from '../entities/achievement.entity';

export const ACHIEVEMENT_DEFINITIONS = [
  // ==================== PRECISION (🏆) - Skill-based ====================
  {
    key: 'first_bet',
    name: 'Premier Pari',
    description: 'Placer votre premier pari',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.COMMON,
    icon: '🏆',
    xpReward: 10,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'perfect_podium',
    name: 'Podium Parfait',
    description: 'Prédire le podium exact',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.COMMON,
    icon: '🏆',
    xpReward: 10,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'perfect_podium_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'perfectBets',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'seer',
    name: 'Voyant',
    description: '3 podiums parfaits',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '🔮',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'perfect_podium_chain',
    prerequisiteAchievementKey: 'perfect_podium',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'perfectBets',
      operator: AchievementConditionOperator.GTE,
      value: 3,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'oracle',
    name: 'Oracle',
    description: '10 podiums parfaits',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.EPIC,
    icon: '🔮',
    xpReward: 250,
    unlocksTitle: 'Oracle',
    tierLevel: 3,
    chainName: 'perfect_podium_chain',
    prerequisiteAchievementKey: 'seer',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'perfectBets',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'perfect_prophet',
    name: 'Le Prophète',
    description: '25 podiums parfaits',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏆',
    xpReward: 500,
    unlocksTitle: 'Le Prophète',
    tierLevel: 4,
    chainName: 'perfect_podium_chain',
    prerequisiteAchievementKey: 'oracle',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'perfectBets',
      operator: AchievementConditionOperator.GTE,
      value: 25,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'sniper',
    name: 'Sniper',
    description: '10 paris avec 2/3 picks corrects',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '🎯',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'partialWins',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'sharpshooter',
    name: "Tireur d'élite",
    description: '50% win rate sur 20+ paris',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.EPIC,
    icon: '🎯',
    xpReward: 250,
    unlocksTitle: 'Sniper',
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate',
      operator: AchievementConditionOperator.GTE,
      value: 50,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'expert_bettor',
    name: 'Parieur Expert',
    description: '75% win rate sur 20+ paris',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏆',
    xpReward: 500,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate',
      operator: AchievementConditionOperator.GTE,
      value: 75,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== REGULARITY (🌟) - Engagement ====================
  {
    key: 'newcomer',
    name: 'Nouvel Arrivant',
    description: '10 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.COMMON,
    icon: '🌟',
    xpReward: 15,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'participation_chain',
    prerequisiteAchievementKey: 'first_bet',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'five_bets',
    name: 'Habitué',
    description: '50 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🌟',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'participation_chain',
    prerequisiteAchievementKey: 'newcomer',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 50,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'twenty_bets',
    name: 'Vétéran',
    description: '200 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🌟',
    xpReward: 300,
    unlocksTitle: null,
    tierLevel: 3,
    chainName: 'participation_chain',
    prerequisiteAchievementKey: 'five_bets',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 200,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'fifty_bets',
    name: 'Légende Vivante',
    description: '500 paris placés',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '⭐',
    xpReward: 1000,
    unlocksTitle: 'La Légende',
    tierLevel: 4,
    chainName: 'participation_chain',
    prerequisiteAchievementKey: 'twenty_bets',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'betsPlaced',
      operator: AchievementConditionOperator.GTE,
      value: 500,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'weekly_warrior',
    name: 'Guerrier Hebdo',
    description: '4 semaines consécutives',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🔥',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'monthlyStreak',
      operator: AchievementConditionOperator.GTE,
      value: 4,
    },
  },
  {
    key: 'monthly_master',
    name: 'Maître Mensuel',
    description: '12 semaines consécutives',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🔥',
    xpReward: 300,
    unlocksTitle: 'Régulier',
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'monthlyStreak',
      operator: AchievementConditionOperator.GTE,
      value: 12,
    },
  },
  {
    key: 'iron_streak',
    name: 'Série de Fer',
    description: 'Record lifetime 20 semaines',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '⭐',
    xpReward: 500,
    unlocksTitle: "L'Invincible",
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'lifetimeStreak',
      operator: AchievementConditionOperator.GTE,
      value: 20,
    },
  },
  {
    key: 'never_give_up',
    name: 'Jamais Abandonner',
    description: 'Parier après 5 semaines perdantes',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '💪',
    xpReward: 150,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'comebackBets',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== AUDACITY (🎯) - Risk-taking ====================
  {
    key: 'first_boost',
    name: 'Première Turbo',
    description: 'Utiliser le boost x2',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.COMMON,
    icon: '⚡',
    xpReward: 20,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'boostsUsed',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'boost_master',
    name: 'Maître Turbo',
    description: 'Utiliser boost 3 mois consécutifs',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.RARE,
    icon: '⚡',
    xpReward: 150,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveBoostMonths',
      operator: AchievementConditionOperator.GTE,
      value: 3,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'turbo_king',
    name: 'Roi Turbo',
    description: 'Utiliser boost 6 mois consécutifs',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '⚡',
    xpReward: 500,
    unlocksTitle: 'Turbo King',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveBoostMonths',
      operator: AchievementConditionOperator.GTE,
      value: 6,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'high_roller',
    name: 'Flambeur',
    description: 'Parier sur outsider (odds > 10) et gagner',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.EPIC,
    icon: '🎲',
    xpReward: 250,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'highOddsWins',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'all_in',
    name: 'All-In',
    description: 'Boost sur outsider (odds > 10) et gagner',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🎲',
    xpReward: 500,
    unlocksTitle: 'Le Flambeur',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'boostedHighOddsWins',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== RANKING (🏅) - Competitive ====================
  {
    key: 'top_ten',
    name: 'Top 10',
    description: 'Terminer dans le top 10 mensuel',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.RARE,
    icon: '🏅',
    xpReward: 100,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.LTE,
      value: 10,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'podium_finish',
    name: 'Sur le Podium',
    description: 'Terminer dans le top 3 mensuel',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '🥉',
    xpReward: 300,
    unlocksTitle: null,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.LTE,
      value: 3,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'monthly_champion',
    name: 'Champion Mensuel',
    description: 'Terminer 1er du mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏆',
    xpReward: 500,
    unlocksTitle: 'Champion',
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.EQ,
      value: 1,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'back_to_back',
    name: 'Double Champion',
    description: '1er deux mois consécutifs',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '👑',
    xpReward: 1000,
    unlocksTitle: 'Dominateur',
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveMonthlyWins',
      operator: AchievementConditionOperator.GTE,
      value: 2,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'points_machine',
    name: 'Machine à Points',
    description: 'Gagner 500 points en un mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '💯',
    xpReward: 250,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'totalPoints',
      operator: AchievementConditionOperator.GTE,
      value: 500,
      scope: AchievementScope.MONTHLY,
    },
  },

  // ==================== AUDACITY CHAIN - Monthly Points ====================
  {
    key: 'point_counter',
    name: 'Compteur de Points',
    description: 'Gagner 200 points en un mois',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.RARE,
    icon: '💯',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'monthly_points_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'totalPoints',
      operator: AchievementConditionOperator.GTE,
      value: 200,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'accumulator',
    name: 'Accumulateur',
    description: 'Gagner 500 points en un mois',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.EPIC,
    icon: '💰',
    xpReward: 250,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'monthly_points_chain',
    prerequisiteAchievementKey: 'point_counter',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'totalPoints',
      operator: AchievementConditionOperator.GTE,
      value: 500,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'bulldozer',
    name: 'Bulldozer',
    description: 'Gagner 1000 points en un mois',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🚜',
    xpReward: 500,
    unlocksTitle: 'Le Bulldozer',
    tierLevel: 3,
    chainName: 'monthly_points_chain',
    prerequisiteAchievementKey: 'accumulator',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'totalPoints',
      operator: AchievementConditionOperator.GTE,
      value: 1000,
      scope: AchievementScope.MONTHLY,
    },
  },

  // ==================== RANKING CHAIN - Win Streaks ====================
  {
    key: 'lucky_streak',
    name: 'Série Chanceuse',
    description: '3 victoires consécutives (semaines)',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.RARE,
    icon: '🍀',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'win_streak_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveWins',
      operator: AchievementConditionOperator.GTE,
      value: 3,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'golden_streak',
    name: 'Série Dorée',
    description: '5 victoires consécutives (semaines)',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '⭐',
    xpReward: 300,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'win_streak_chain',
    prerequisiteAchievementKey: 'lucky_streak',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveWins',
      operator: AchievementConditionOperator.GTE,
      value: 5,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'legendary_streak',
    name: 'Série Légendaire',
    description: '10 victoires consécutives (semaines)',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '👑',
    xpReward: 800,
    unlocksTitle: "L'Implacable",
    tierLevel: 3,
    chainName: 'win_streak_chain',
    prerequisiteAchievementKey: 'golden_streak',
    isTemporary: false,
    canBeLost: false,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'consecutiveWins',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== TEMPORARY ACHIEVEMENTS ====================
  // Type: Monthly Ranking
  {
    key: 'bronze_medal',
    name: 'Médaille de Bronze',
    description: 'Terminer dans le top 3 ce mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.RARE,
    icon: '🥉',
    xpReward: 150,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.LTE,
      value: 3,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'silver_medal',
    name: "Médaille d'Argent",
    description: 'Terminer 2e ce mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '🥈',
    xpReward: 250,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.EQ,
      value: 2,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'gold_medal',
    name: "Médaille d'Or",
    description: 'Terminer 1er ce mois',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🥇',
    xpReward: 500,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.RANKING,
      metric: 'rank',
      operator: AchievementConditionOperator.EQ,
      value: 1,
      scope: AchievementScope.MONTHLY,
    },
  },

  // Type: Recent Performance (30-day rolling window)
  {
    key: 'in_form',
    name: 'En Forme',
    description: '60% winrate sur 30 derniers jours (min 10 paris)',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '💪',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate30Days',
      operator: AchievementConditionOperator.GTE,
      value: 60,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'olympic_form',
    name: 'Forme Olympique',
    description: '75% winrate sur 30 derniers jours (min 15 paris)',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.EPIC,
    icon: '🏅',
    xpReward: 250,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate30Days',
      operator: AchievementConditionOperator.GTE,
      value: 75,
      scope: AchievementScope.MONTHLY,
    },
  },
  {
    key: 'invincible',
    name: 'Invincible',
    description: '90% winrate sur 30 derniers jours (min 20 paris)',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.LEGENDARY,
    icon: '⚡',
    xpReward: 500,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'winRate30Days',
      operator: AchievementConditionOperator.GTE,
      value: 90,
      scope: AchievementScope.MONTHLY,
    },
  },

  // Type: Active Streak
  {
    key: 'active_streak',
    name: 'Série Active',
    description: '5 semaines consécutives actives',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🔥',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'monthlyStreak',
      operator: AchievementConditionOperator.GTE,
      value: 5,
    },
  },
  {
    key: 'marathon',
    name: 'Marathon',
    description: '10 semaines consécutives actives',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🏃',
    xpReward: 300,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: true,
    canBeLost: true,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'monthlyStreak',
      operator: AchievementConditionOperator.GTE,
      value: 10,
    },
  },
];
