import {
  AchievementCategory,
  AchievementDomain,
  AchievementRarity,
  AchievementConditionType,
  AchievementConditionOperator,
  AchievementScope,
} from '../entities/achievement.entity';

export const ACHIEVEMENT_DEFINITIONS = [
  // ==================== RACING - Victoires en course ====================
  {
    key: 'first_win',
    name: 'Première Victoire',
    description: 'Remporter votre première course',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.COMMON,
    icon: '🏁',
    xpReward: 10,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'race_wins_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorTotalWins',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'five_wins',
    name: 'Quintuple Vainqueur',
    description: '5 victoires en course',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.RARE,
    icon: '🏁',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'race_wins_chain',
    prerequisiteAchievementKey: 'first_win',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorTotalWins',
      operator: AchievementConditionOperator.GTE,
      value: 5,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'twenty_wins',
    name: 'Dominateur de Piste',
    description: '20 victoires en course',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '🏁',
    xpReward: 250,
    unlocksTitle: null,
    tierLevel: 3,
    chainName: 'race_wins_chain',
    prerequisiteAchievementKey: 'five_wins',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorTotalWins',
      operator: AchievementConditionOperator.GTE,
      value: 20,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'fifty_wins',
    name: 'Maître des Courses',
    description: '50 victoires en course',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🏁',
    xpReward: 500,
    unlocksTitle: 'Maître des Courses',
    tierLevel: 4,
    chainName: 'race_wins_chain',
    prerequisiteAchievementKey: 'twenty_wins',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorTotalWins',
      operator: AchievementConditionOperator.GTE,
      value: 50,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== RACING - Participation ====================
  {
    key: 'first_race',
    name: 'Baptême de Feu',
    description: 'Participer à votre première course',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.COMMON,
    icon: '🏎️',
    xpReward: 10,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'race_participation_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorRaceCount',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'ten_races',
    name: 'Coureur Régulier',
    description: '10 courses disputées',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.COMMON,
    icon: '🏎️',
    xpReward: 15,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'race_participation_chain',
    prerequisiteAchievementKey: 'first_race',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorRaceCount',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'fifty_races',
    name: 'Marathonien',
    description: '50 courses disputées',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🏎️',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 3,
    chainName: 'race_participation_chain',
    prerequisiteAchievementKey: 'ten_races',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorRaceCount',
      operator: AchievementConditionOperator.GTE,
      value: 50,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'hundred_races',
    name: 'Centurion',
    description: '100 courses disputées',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🏎️',
    xpReward: 300,
    unlocksTitle: 'Centurion',
    tierLevel: 4,
    chainName: 'race_participation_chain',
    prerequisiteAchievementKey: 'fifty_races',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'competitorRaceCount',
      operator: AchievementConditionOperator.GTE,
      value: 100,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== RACING - ELO Rating ====================
  {
    key: 'elo_1600',
    name: 'Compétiteur Solide',
    description: 'Atteindre 1100 de score ELO',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.COMMON,
    icon: '📈',
    xpReward: 20,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'elo_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'competitorRating',
      operator: AchievementConditionOperator.GTE,
      value: 1100,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'elo_1700',
    name: 'Challenger',
    description: 'Atteindre 1300 de score ELO',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '📈',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'elo_chain',
    prerequisiteAchievementKey: 'elo_1600',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'competitorRating',
      operator: AchievementConditionOperator.GTE,
      value: 1300,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'elo_1800',
    name: 'Élite',
    description: 'Atteindre 1500 de score ELO',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.EPIC,
    icon: '📈',
    xpReward: 300,
    unlocksTitle: 'Élite',
    tierLevel: 3,
    chainName: 'elo_chain',
    prerequisiteAchievementKey: 'elo_1700',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'competitorRating',
      operator: AchievementConditionOperator.GTE,
      value: 1500,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'elo_2000',
    name: 'Grand Maître',
    description: 'Atteindre 1700 de score ELO',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.LEGENDARY,
    icon: '📈',
    xpReward: 500,
    unlocksTitle: 'Grand Maître',
    tierLevel: 4,
    chainName: 'elo_chain',
    prerequisiteAchievementKey: 'elo_1800',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'competitorRating',
      operator: AchievementConditionOperator.GTE,
      value: 1700,
      scope: AchievementScope.LIFETIME,
    },
  },

  // ==================== RACING - Win Streak ====================
  {
    key: 'race_win_streak_3',
    name: 'Triplette',
    description: '3 victoires consécutives en course',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.RARE,
    icon: '🔥',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'race_win_streak_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'competitorWinStreak',
      operator: AchievementConditionOperator.GTE,
      value: 3,
    },
  },
  {
    key: 'race_win_streak_5',
    name: 'Main Chaude',
    description: '5 victoires consécutives en course',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.EPIC,
    icon: '🔥',
    xpReward: 300,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'race_win_streak_chain',
    prerequisiteAchievementKey: 'race_win_streak_3',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'competitorWinStreak',
      operator: AchievementConditionOperator.GTE,
      value: 5,
    },
  },
  {
    key: 'race_win_streak_10',
    name: 'Inarrêtable',
    description: '10 victoires consécutives record en course',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🔥',
    xpReward: 800,
    unlocksTitle: 'Inarrêtable',
    tierLevel: 3,
    chainName: 'race_win_streak_chain',
    prerequisiteAchievementKey: 'race_win_streak_5',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'competitorBestWinStreak',
      operator: AchievementConditionOperator.GTE,
      value: 10,
    },
  },

  // ==================== RACING - Play Streak ====================
  {
    key: 'race_play_streak_5',
    name: 'Assidu',
    description: '5 jours de participation consécutifs',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '📅',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'race_play_streak_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'competitorPlayStreak',
      operator: AchievementConditionOperator.GTE,
      value: 5,
    },
  },
  {
    key: 'race_play_streak_10',
    name: 'Infatigable',
    description: '10 jours consécutifs de participation',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '📅',
    xpReward: 250,
    unlocksTitle: 'Infatigable',
    tierLevel: 2,
    chainName: 'race_play_streak_chain',
    prerequisiteAchievementKey: 'race_play_streak_5',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'competitorPlayStreak',
      operator: AchievementConditionOperator.GTE,
      value: 10,
    },
  },

  // ==================== RACING - Performance ====================
  {
    key: 'podium_avg',
    name: 'Habitué du Podium',
    description: 'Moyenne classement ≤ 3 sur les 12 dernières courses',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.EPIC,
    icon: '🥇',
    xpReward: 250,
    unlocksTitle: null,
    tierLevel: 0,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.RACING,
    condition: {
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'competitorAvgRank12',
      operator: AchievementConditionOperator.LTE,
      value: 3,
      scope: AchievementScope.LIFETIME,
      minCount: { metric: 'competitorRaceCount', value: 12 },
    },
  },

  /* ==================== PING-PONG ==================== */
  //
  // Calibrated for a 25-person office. Two design constraints drove these:
  //
  // 1. Achievements must counterbalance the Glicko leaderboard, not echo it.
  //    In a small group only the top few ever climb the table, so a "reach
  //    1800" badge rewards the same three people forever. Most conditions
  //    below are reachable regardless of standing — volume, variety, match
  //    moments — and `pp_le_tombeur` is deliberately EASIER the lower you are.
  //
  // 2. Rarity has to fall away sharply. With 25 players, "under 5%" means one
  //    person — which is the point of a LEGENDARY, but two is the maximum
  //    before the trophy case just looks empty to everyone else.

  {
    key: 'pp_premier_service',
    name: 'Premier Service',
    description: 'Jouer son premier match de ping-pong',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.COMMON,
    icon: '🏓',
    xpReward: 50,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'pingpong_volume_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongMatchCount',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_habitue_de_la_table',
    name: 'Habitué de la Table',
    description: '25 matchs au compteur. On commence à te reconnaître.',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.COMMON,
    icon: '🏓',
    xpReward: 150,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'pingpong_volume_chain',
    prerequisiteAchievementKey: 'pp_premier_service',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongMatchCount',
      operator: AchievementConditionOperator.GTE,
      value: 25,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_pilier_du_bureau',
    name: 'Pilier du Bureau',
    description: '100 matchs. La table a ton nom gravé dessus.',
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.RARE,
    icon: '🏛️',
    xpReward: 400,
    unlocksTitle: null,
    tierLevel: 3,
    chainName: 'pingpong_volume_chain',
    prerequisiteAchievementKey: 'pp_habitue_de_la_table',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongMatchCount',
      operator: AchievementConditionOperator.GTE,
      value: 100,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_institution',
    name: 'Institution',
    description:
      "250 matchs. Tu fais partie du mobilier, et c'est un compliment.",
    category: AchievementCategory.REGULARITY,
    rarity: AchievementRarity.EPIC,
    icon: '🏆',
    xpReward: 1000,
    unlocksTitle: 'Institution',
    tierLevel: 4,
    chainName: 'pingpong_volume_chain',
    prerequisiteAchievementKey: 'pp_pilier_du_bureau',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongMatchCount',
      operator: AchievementConditionOperator.GTE,
      value: 250,
      scope: AchievementScope.LIFETIME,
    },
  },

  {
    key: 'pp_deux_dafilee',
    name: "Deux d'Affilée",
    description: 'Deux victoires de suite. Ça sent le début de quelque chose.',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.COMMON,
    icon: '✌️',
    xpReward: 75,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: 'pingpong_streak_chain',
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'pingpongBestStreak',
      operator: AchievementConditionOperator.GTE,
      value: 2,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_en_chaleur',
    name: 'En Chaleur',
    description:
      "5 victoires d'affilée. Plus personne ne veut prendre la raquette.",
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.RARE,
    icon: '🔥',
    xpReward: 350,
    unlocksTitle: null,
    tierLevel: 2,
    chainName: 'pingpong_streak_chain',
    prerequisiteAchievementKey: 'pp_deux_dafilee',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'pingpongBestStreak',
      operator: AchievementConditionOperator.GTE,
      value: 5,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_intouchable',
    name: 'Intouchable',
    description:
      '10 victoires consécutives. On organise une cagnotte pour te faire tomber.',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.LEGENDARY,
    icon: '👑',
    xpReward: 1500,
    unlocksTitle: 'Intouchable',
    tierLevel: 3,
    chainName: 'pingpong_streak_chain',
    prerequisiteAchievementKey: 'pp_en_chaleur',
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.STREAK,
      metric: 'pingpongBestStreak',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },

  {
    key: 'pp_tour_du_bureau',
    name: 'Le Tour du Bureau',
    description:
      '10 adversaires différents en trois semaines. Tu ne fuis personne.',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.RARE,
    icon: '🌍',
    xpReward: 350,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongDistinctOpponents',
      operator: AchievementConditionOperator.GTE,
      value: 10,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_calibre',
    name: 'Calibré',
    description:
      'Assez de matchs variés pour que ton classement veuille dire quelque chose',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.COMMON,
    icon: '🎯',
    xpReward: 200,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      // Reads the WEIGHTED count on purpose: eight matches against the same
      // opponent should not buy you out of calibration.
      type: AchievementConditionType.COUNT,
      metric: 'pingpongWeightedMatchCount',
      operator: AchievementConditionOperator.GTE,
      value: 8,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_maitre_du_tapis',
    name: 'Maître du Tapis',
    description: 'Atteindre 1700 au classement ping-pong',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '⭐',
    xpReward: 800,
    unlocksTitle: 'Maître du Tapis',
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      // pingpongRating is the conservative score, so a fresh player with a
      // lucky streak and a wide deviation cannot slip through.
      type: AchievementConditionType.STAT_THRESHOLD,
      metric: 'pingpongRating',
      operator: AchievementConditionOperator.GTE,
      value: 1700,
      scope: AchievementScope.LIFETIME,
      minCount: { metric: 'pingpongWeightedMatchCount', value: 20 },
    },
  },

  // ---------------------------------------------------------------------
  // Per-match feats.
  //
  // These read tallies replayed from the match log rather than a column on
  // the player, because they live in the shape of a single match: a player
  // can hold three hundred wins and never once have taken a set 11-0.
  // ---------------------------------------------------------------------

  {
    key: 'pp_la_bulle',
    name: 'La Bulle',
    description: 'Gagner un set 11-0. Pas un point. Pas un seul.',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '⭕',
    xpReward: 300,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongShutoutSetsDealt',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_creme_fraiche',
    name: 'Crème Fraîche',
    description:
      'Prendre un set 0-11. Ça arrive aux meilleurs. Enfin, surtout aux autres.',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.COMMON,
    icon: '🥛',
    xpReward: 100,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongShutoutSetsConceded',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_retour_des_enfers',
    name: 'Retour des Enfers',
    description: 'Perdre le premier set et gagner le match quand même',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.COMMON,
    icon: '🔥',
    xpReward: 150,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongComebacks',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_a_larrache',
    name: "À l'Arrache",
    description: 'Gagner cinq sets au-delà de 10-10. Les nerfs tiennent.',
    category: AchievementCategory.PRECISION,
    rarity: AchievementRarity.RARE,
    icon: '😰',
    xpReward: 350,
    unlocksTitle: null,
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongDeuceSetsWon',
      operator: AchievementConditionOperator.GTE,
      value: 5,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_le_tombeur',
    name: 'Le Tombeur',
    description: 'Battre un joueur classé 150 points au-dessus de toi',
    category: AchievementCategory.RANKING,
    rarity: AchievementRarity.EPIC,
    icon: '🗡️',
    xpReward: 600,
    unlocksTitle: 'Le Tombeur',
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      type: AchievementConditionType.COUNT,
      metric: 'pingpongUpsets',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
  {
    key: 'pp_le_casse',
    name: 'Le Casse',
    description:
      'Premier set perdu, puis deux sets arrachés au-delà de 10-10. Du grand art.',
    category: AchievementCategory.AUDACITY,
    rarity: AchievementRarity.LEGENDARY,
    icon: '🎭',
    xpReward: 1500,
    unlocksTitle: 'Le Casse',
    tierLevel: 1,
    chainName: null,
    prerequisiteAchievementKey: null,
    isTemporary: false,
    canBeLost: false,
    domain: AchievementDomain.PINGPONG,
    condition: {
      // Deliberately narrow. On a 25-player league this may go unclaimed for
      // months, which is what "legendary" is supposed to mean.
      type: AchievementConditionType.COUNT,
      metric: 'pingpongHeists',
      operator: AchievementConditionOperator.GTE,
      value: 1,
      scope: AchievementScope.LIFETIME,
    },
  },
];
