version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: activscanio-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: activscanio
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: activscanio-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: activscanio
    ports:
      - '3000:3000'
    volumes:
      - .:/app

volumes:
  db-data:
