version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: activscanio-db
    # On expose le port si on veut y accéder depuis la machine hôte
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: activscanio
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - activscanio-net

  api:
    build: .
    container_name: activscanio-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: secret
      DB_NAME: activscanio
    ports:
      - '3000:3000'
    networks:
      - activscanio-net

volumes:
  db-data:

networks:
  activscanio-net:
    external: true
