services:
  db:
    container_name: activscanio-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  activscanio-api:
    container_name: activscanio-api
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      NODE_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - '3000:3000'
    command: npm run start:prod

volumes:
  db-data:
