services:
  db:
    image: postgres:15-alpine
    container_name: activscanio-db-staging
    # Tu peux exposer ou non, selon tes besoins
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  activscanio-api:
    build:
      context: .
    container_name: activscanio-api-staging
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - '3000:3000'
    command: npm run start:prod

volumes:
  db-data:
