export enum XPSource {
  // Existing sources
  BET_PLACED = 'BET_PLACED',
  CORRECT_PICK = 'CORRECT_PICK',
  PERFECT_PODIUM = 'PERFECT_PODIUM',
  WEEKLY_PARTICIPATION = 'WEEKLY_PARTICIPATION',
  STREAK_MAINTAINED = 'STREAK_MAINTAINED',
  ACHIEVEMENT_COMMON = 'ACHIEVEMENT_COMMON',
  ACHIEVEMENT_RARE = 'ACHIEVEMENT_RARE',
  ACHIEVEMENT_EPIC = 'ACHIEVEMENT_EPIC',
  ACHIEVEMENT_LEGENDARY = 'ACHIEVEMENT_LEGENDARY',
  LEVEL_UP_BONUS = 'LEVEL_UP_BONUS',

  // New sources
  DAILY_LOGIN_BONUS = 'DAILY_LOGIN_BONUS',
  DAILY_FIRST_BET_BONUS = 'DAILY_FIRST_BET_BONUS',
  WEEKLY_STREAK_BONUS = 'WEEKLY_STREAK_BONUS',
  HIGH_ODDS_BONUS = 'HIGH_ODDS_BONUS',
  PERFECT_WEEK_BONUS = 'PERFECT_WEEK_BONUS',
  COMEBACK_BONUS = 'COMEBACK_BONUS',
}
